- name: download homebrew
  shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    creates: /usr/local/bin/brew
  when: ansible_facts['os_family'] == "Darwin"

- name: download linuxbrew
  shell:
    cmd: |
      git clone --depth 1 https://github.com/Homebrew/brew "$HOME/.linuxbrew/Homebrew"
      mkdir "$HOME/.linuxbrew/bin"
      ln -s "$HOME/.linuxbrew/Homebrew/bin/brew" "$HOME/.linuxbrew/bin"
      eval "$("$HOME/.linuxbrew/bin/brew" shellenv)"
    creates: $HOME/.linuxbrew/bin/brew
  when: ansible_facts['os_family'] == "Linux"

- name: homebrew update
  homebrew:
    update_homebrew: true

- name: brew tap
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ taps }}"

- name: brew install
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: brew cask install
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ cask_packages }}"
