#!/bin/bash

_install() {
  local name=${1##*/}
  if grep ^https <<<$1; then
    git clone --depth 1 "$1.git" "$HOME/.vim/pack/plug/start/${name}"
  else
    git clone --depth 1 "https://github.com/$1.git" "$HOME/.vim/pack/plug/start/${name}"
  fi
}

_uninstall() {
  local name=${1##*/}
  [[ -d "$HOME/.vim/pack/plug/start/${name}" ]] && rm -rf "$HOME/.vim/pack/plug/start/${name}"
  [[ -d "$HOME/.vim/pack/plug/disabled/${name}" ]] && rm -rf "$HOME/.vim/pack/plug/disabled/${name}"
}

_list() {
  echo "*** active ***"
  \ls "$HOME/.vim/pack/plug/start/" | cat
  echo ""
  echo "*** disabled ***"
  \ls "$HOME/.vim/pack/plug/disabled/" | cat
}

_disable() {
  local name=${1##*/}
  if [[ ! -d "$HOME/.vim/pack/plug/disabled" ]]; then
    mkdir "$HOME/.vim/pack/plug/disabled"
  fi
  mv "$HOME/.vim/pack/plug/start/${name}" "$HOME/.vim/pack/plug/disabled/${name}"
}

_enable() {
  local name=${1##*/}
  mv "$HOME/.vim/pack/plug/disabled/${name}" "$HOME/.vim/pack/plug/start/${name}"
}

_help() {
  cat <<EOF
Plug - Simple vim plugin installer

Usage:
  plug install <owner>/<repo>
  plug uninstall [<owner>/]<repo>
  plug ls
  plug enable [<owner>/]<repo>
  plug disable [<owner>/]<repo>

Commands:
  install     Install plugin
  uninstall   Uninstall plugin
  ls          List installed plugins
  enable      Enable plugins
  disable     Disable plugins
EOF
  exit 0
}

case "$1" in
"install")
  for plugin in "${@:2}"; do
    _install "${plugin}" &
  done
  wait
  ;;
"uninstall")
  for plugin in "${@:2}"; do
    _uninstall "${plugin}" &
  done
  wait
  ;;
"ls")
  _list
  ;;
"enable")
  for plugin in "${@:2}"; do
    _enable "${plugin}" &
  done
  wait
  ;;
"disable")
  for plugin in "${@:2}"; do
    _disable "${plugin}" &
  done
  wait
  ;;
"-h" | "--help")
  _help
  ;;
*)
  echo "Unknown command: $1"
  _help
  ;;
esac
