tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "sanemat/font"
brew "ansible"
brew "bash"
brew "bat"
brew "coreutils"
brew "ctags"
brew "docker"
brew "docker-compose"
brew "fzf"
brew "ghq"
brew "hub"
brew "jq"
brew "mas"
brew "micro"
brew "neovim", args: ["HEAD"]
brew "node"
brew "pipenv"
brew "ranger"
brew "ripgrep"
brew "tig"
brew "tmux"
brew "tree"
cask "alacritty"
cask "dbeaver-community"
cask "eclipse-java"
cask "firefox"
cask "font-cica"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "java"
cask "meld"
cask "slack"
cask "vagrant"
cask "visual-studio-code"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Todoist", id: 585829637
