# dein_lazy.toml

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    nnoremap [denite]    <Nop>
    nmap     <Space>u [denite]

    nnoremap <silent> [denite]d :<C-u>DeniteBufferDir file file:new<CR>
    nnoremap <silent> [denite]b :<C-u>Denite buffer<CR>
    nnoremap <silent> [denite]f :<C-u>Denite file<CR>
    nnoremap <silent> [denite]r :<C-u>Denite file_rec<CR>
    nnoremap <silent> [denite]l :<C-u>Denite line<CR>
    nnoremap <silent> [denite]g :<C-u>Denite -auto-preview grep<CR>
'''
hook_post_source = '''
    call denite#custom#option('default', 'prompt', '>')
    call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>', 'noremap')
    call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>', 'noremap')

    " Ripgrep command as grep source
    call denite#custom#var('grep', 'command', ['rg'])
    call denite#custom#var('grep', 'default_opts',
                \ ['-i', '--vimgrep', '--no-heading'])
    call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
    call denite#custom#var('grep', 'separator', ['--'])
    call denite#custom#var('grep', 'final_opts', [])
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
    call deoplete#enable()
'''

# on file-type plugins
[[plugins]]
repo = 'mattn/emmet-vim')
on_ft = ['html', 'xml']

[[plugins]]
repo = 'iwataka/minidown.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['haskell']

#call dein#add('eagletmt/ghcmod-vim') " haskell static analyzer
