# dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
    call togglebg#map('<F5>')
    set background=dark
    colorscheme solarized
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
                \ 'colorscheme': 'solarized',
                \ }
'''

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'nelstrom/vim-visual-star-search'

[[plugins]]
# better than surround.vim
repo = 'machakann/vim-sandwich'

