---
- name: Autohide the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true

- name: Use F1, F2, etc. keys as standard function keys
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.keyboard.fnState
    type: bool
    value: true

- name: Enable to use installed bash as a login shell
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: /opt/homebrew/bin/bash

- name: Change the default shell to bash
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /opt/homebrew/bin/bash
