if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
export BASH_SILENCE_DEPRECATION_WARNING=1
export LANG=ja_JP.UTF-8
export LC_CTYPE=en_US.UTF-8
export TERM=xterm-256color

export PATH="$HOME/.cargo/bin:$PATH"
