.vim/syntax/gotexttmpl.vim:
  type: file
  url: https://raw.githubusercontent.com/fatih/vim-go/master/syntax/gotexttmpl.vim

.vim/pack/minpac/opt/minpac:
  type: git-repo
  url: https://github.com/k-takata/minpac.git

.git-completion.bash:
  type: file
  url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash

.git-prompt.sh:
  type: file
  url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh

.fzf.bash:
  type: file
  url: https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.bash
