version: 2
root-markers:
  - .git/

tools:
  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  python-isort: &python-isort
    format-command: 'isort --quiet -'
    format-stdin: true

  go-staticcheck: &go-staticcheck
    lint-command: 'staticcheck'
    lint-formats:
      - '%f:%l:%c: %m'

  go-errcheck: &go-errcheck
    lint-command: 'errcheck'
    lint-formats:
      - '%f:%l:%c:%m'

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint'
    lint-formats:
      - '%f:%l %m'

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -s -ci -i 2'
    format-stdin: true

  tflint: &tflint
    lint-command: 'tflint --config .tflint.hcl --format compact'
    lint-fomats:
      - '%f:%l:%c: %m'

languages:
  # python:
    # - <<: *python-black
    # - <<: *python-isort

  # go:
  #   - <<: *go-staticcheck
    # - <<: *go-errcheck

  dockerfile:
    - <<: *dockerfile-hadolint

  sh:
    # - <<: *sh-shellcheck
    - <<: *sh-shfmt

  # terraform:
  #   - <<: *tflint
