- name: Dockからデフォルトのアプリを消す
  osx_defaults:
    domain: com.apple.dock
    key: persistent-apps
    type: array
    value:

- name: フォーカスしたDockのアプリを拡大
  osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: bool
    value: True

- name: Finderで不可視ファイルを表示
  osx_defaults:
      domain: com.apple.finder
      key: AppleShowAllFiles
      type: string
      value: YES

- name: バッテリーの％を表示
  osx_defaults:
      domain: com.apple.menuextra.battery
      key: ShowPercent
      type: string
      value: YES
