[[snippet]]
prefix = 'main'
description = 'main'
body = '''
#include <stdio.h>
#include <stdlib.h>

int main(int argc, const char **argv)
{
	$1

	return 0;
}
'''

[[snippet]]
prefix = 'fori'
description = 'for loop'
body = '''
for (int i=0; i<$1; i++) {
	$2
}
'''

# vim: ts=2 noexpandtab
