[[snippet]]
prefix = 'i'
description = 'include'
body = '''
#include <$1.h>
'''

[[snippet]]
prefix = 'i"'
description = 'include'
body = '''
#include "$1.h"
'''

[[snippet]]
prefix = 'main'
description = 'main'
body = '''
int main(int argc, char **argv)
{
	$1
}
'''

[[snippet]]
prefix = 'fopen'
description = 'file open'
body = '''
FILE *fp = fopen(${1:filename}, ${2:mode});
if (fp == NULL) {
  fprintf(stderr, "cannot open %s\n", $1);
  exit(1);
}
fclose(fp);
'''

[[snippet]]
prefix = 'va'
description = 'variadic argument'
body = '''
#include <stdarg.h>
va_list ap;
va_start(ap, ${1:arg});
va_arg(ap, <type>);
va_end;
'''

[[snippet]]
prefix = 'sprintf'
description = 'secure sprintf'
body = '''
size_t size = snprintf(NULL, 0, "$1", $2) + 1;
char *$3 = malloc(sizeof(char) * size);
snprintf($3, size, "$1", $2);
'''
