[[snippet]]
prefix = 'user'
description = 'useradd'
body = '''
ARG USERNAME=user
ARG GROUPNAME=user
ARG UID=1000
ARG GID=1000
RUN groupadd -g \$GID \$GROUPNAME && \
  useradd -m -s /bin/bash -u \$UID -g \$GID \$USERNAME
USER \$USERNAME
WORKDIR /home/\$USERNAME
'''

[[snippet]]
prefix = 'aptget'
description = 'apt-get install'
body = '''
RUN apt-get update && apt-get install -y \
  vim
'''
