[[snippet]]
prefix = 'table'
description = 'table'
body = '''
<table>
	<thead>
		<tr>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td></td>
		</tr>
	</tbody>
</table>
'''

[[snippet]]
prefix = 'select'
description = 'select'
body = '''
<select id="" name="">
	<option value=""></option>
</select>
'''

[[snippet]]
prefix = 'ngfor'
description = 'ngFor'
body = '''
*ngFor="let $1 of $2"
'''

[[snippet]]
prefix = 'ngif'
description = 'ngIf'
body = '''
*ngIf="$1"
'''

[[snippet]]
prefix = 'ngifelse'
description = 'ngIf else'
body = '''
<ng-container *ngIf="$1; else $2">
	$3
</ng-container>
<ng-template #$2>
	$4
</ng-template>
'''

[[snippet]]
prefix = 'ngswitch'
description = 'ngSwitch'
body = '''
<ng-container [ngSwitch]="$1">
	<ng-container *ngSwitchCase="$2">
		$3
	</ng-container>
	<ng-container *ngSwitchDefault>
		$4
	</ng-container>
</ng-container>
'''

# vim: ts=2 noexpandtab
