[[snippet]]
prefix = '%'
description = '% tag'
body = '''
{% $1 %}
'''

[[snippet]]
prefix = 'for'
description = 'django for loop'
body = '''
{% for $1 in $2 %}
	$3
{% endfor %}
'''

[[snippet]]
prefix = 'if'
description = 'django if'
body = '''
{% if $1 %}
	$2
{% else %}
	$3
{% endif %}
'''

[[snippet]]
prefix = 'with'
description = 'django with'
body = '''
{% with $1 as $2 %}
	$2
{% endwith %}
'''
