[[snippet]]
prefix = 'help'
description = 'generate help'
body = '''
.DEFAULT_GOAL := help
.PHONY: help
help: ## Display this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*\$\$' \$(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", \$\$1, \$\$2}'
'''

[[snippet]]
prefix = 'ph'
description = 'phony'
body = '''
.PHONY: $1
$1:
	$2
'''

# vim: ts=2 noexpandtab
