[[snippet]]
prefix = 'bash'
description = 'bash shebang'
body = '''
#!/bin/bash
set -eu
'''

[[snippet]]
prefix = 'dir'
description = 'script dir'
body = '''
SCRIPT_DIR="\$(cd "\$(dirname "\$0")"; pwd)"
'''

[[snippet]]
prefix = 'onexit'
description = 'on exit function'
body = '''
function on_exit() {
	$1
}

trap on_exit EXIT
'''

[[snippet]]
prefix = 'onerr'
description = 'on error function'
body = '''
function on_error() {
	$1
}

trap on_error ERR
'''

[[snippet]]
prefix = 'whileread'
description = 'while read'
body = '''
while read -r col1 col2; do
	$1
done <<EOF
$2
EOF
'''

[[snippet]]
prefix = 'if'
description = 'if statement'
body = '''
if [[ $1 ]]; then
	$2
fi
'''

[[snippet]]
prefix = 'case'
description = 'case statement'
body = '''
case "\${$1}" in
	*)
		$2
		;;
esac
'''

[[snippet]]
prefix = 'fn'
description = 'function'
body = '''
function $1() {
	$2
}
'''

[[snippet]]
prefix = 'log'
description = 'logging function'
body = '''
function log() {
	local severity="\$1"
	local message="\${@:2}"
	echo "[\${severity}] \${message}" 1>&2
}
'''

[[snippet]]
prefix = 'retry'
description = 'with retry function'
body = '''
function with_retry() {
	local -r max_retry="\$1"
	local -r cmd="\${@:2}"

	for retry_count in \$(seq 0 \${max_retry}); do
		log INFO \${cmd} "retry_count=\${retry_count}"
		\${cmd} && return 0
	done

	log ERROR "max retry exceeded: \${cmd}"
	return 1
}
'''

[[snippet]]
prefix = 'lock'
description = 'lock file'
body = '''
# symlinkはすでに作成されている場合失敗するのでロックに使える
if ! ln -s \$\$ ./\$\$.lock; then
	echo locked
	exit 0
fi
'''

[[snippet]]
prefix = 'confirm'
description = 'confirm'
body = '''
read -p "Are you sure? (y/N): " YN
if [[ "\${YN}" != 'y' ]]; then
	echo 'abort.' 1>&2
	exit 1
fi
'''

[[snippet]]
prefix = 'opts'
description = 'parse options'
body = '''
while [[ \$# -gt 0 ]]; do
	case "\$1" in
		-o | -o=*)
			if [[ \$1 =~ ^-o= ]]; then
				echo option o is \${1#*=}
			else
				echo option o is \$2
				shift
			fi
			;;
		-h)
			echo h
			;;
		*)
			echo \$1
			;;
	esac
	shift
done
'''

[[snippet]]
prefix = '$'
description = 'variable'
body = '''
"\${$1}"
'''

[[snippet]]
prefix = 'reg'
description = 'region option'
body = '''
--region $1
'''

[[snippet]]
prefix = 'pro'
description = 'profile option'
body = '''
--profile $1
'''

[[snippet]]
prefix = 'tex'
description = 'output text option'
body = '''
--output text
'''

# vim: ts=2 noexpandtab
