[[snippet]]
prefix = 'var'
description = 'variable block'
body = '''
variable "$1" {
	type = $2
}
'''

[[snippet]]
prefix = 'res'
description = 'resource block'
body = '''
resource "$1" "$2" {
	$3
}
'''

[[snippet]]
prefix = 'mod'
description = 'module block'
body = '''
module "$1" {
	$2
}
'''

[[snippet]]
prefix = 'out'
description = 'output'
body = '''
output "$1" {
	value = $2
}
'''

[[snippet]]
prefix = 'loc'
description = 'locals'
body = '''
locals {
	$1
}
'''

[[snippet]]
prefix = 'provider'
description = 'provider'
body = '''
provider "aws" {
	region  = $1
	profile = $2
	assume_role {
		role_arn = $3
	}
	default_tags {
		tags = {
			Environment = $4
			Service     = $5
		}
	}
}
'''

[[snippet]]
prefix = 'version'
description = 'version'
body = '''
terraform {
	required_version = "$1"
	required_providers {
		aws = {
			source  = "hashicorp/aws"
			version = "$2"
		}
	}
}
'''

[[snippet]]
prefix = 'backend'
description = 'backend'
body = '''
terraform {
	backend "s3" {
		region                  = "$1"
		encrypt                 = true
		bucket                  = "$2"
		key                     = "$3"
		shared_credentials_file = "$4"
		profile                 = "$5"
	}
}
'''
