[[snippet]]
prefix = 'var'
description = 'variable block'
body = '''
variable "$1" {
	description = "$2"
	type = $3
}
'''

[[snippet]]
prefix = 'res'
description = 'resource block'
body = '''
resource "$1" "$2" {
	$3
}
'''

[[snippet]]
prefix = 'data'
description = 'data source'
body = '''
data "$1" "$2" {
	$3
}
'''

[[snippet]]
prefix = 'mod'
description = 'module block'
body = '''
module "$1" {
	source = "$2"

	$3
	providers = {
		$4
	}
}
'''

[[snippet]]
prefix = 'out'
description = 'output'
body = '''
output "$1" {
	description = "$2"
	value = $3
}
'''

[[snippet]]
prefix = 'loc'
description = 'locals'
body = '''
locals {
	$1
}
'''

[[snippet]]
prefix = 'provider'
description = 'provider'
body = '''
provider "aws" {
	region  = $1
	assume_role {
		role_arn = $3
	}
	default_tags {
		tags = {
			Environment = $4
			Service     = $5
		}
	}
}
'''

[[snippet]]
prefix = 'version'
description = 'version'
body = '''
terraform {
	required_version = "$1"
	required_providers {
		aws = {
			source  = "hashicorp/aws"
			version = "$2"
		}
	}
}
'''

[[snippet]]
prefix = 'backend'
description = 'backend'
body = '''
terraform {
	backend "s3" {
		region                  = "$1"
		encrypt                 = true
		bucket                  = "$2"
		key                     = "$3"
	}
}
'''

[[snippet]]
prefix = 'caller'
description = 'aws caller identity'
body = '''
data "aws_caller_identity" "self" {}
'''

# vim: ts=2 noexpandtab
