---
- name: Download files
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
      dest: "{{ ansible_env.HOME }}/.git-completion.bash"
      mode: "0644"
    - url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
      dest: "{{ ansible_env.HOME }}/.git-prompt.sh"
      mode: "0644"
    - url: https://raw.githubusercontent.com/git/git/master/contrib/git-jump/git-jump
      dest: "{{ ansible_env.HOME }}/.local/bin/git-jump"
      mode: "0755"
    - url: https://raw.githubusercontent.com/junegunn/fzf/refs/heads/master/shell/key-bindings.bash
      dest: "{{ ansible_env.HOME }}/.fzf-key-bindings.bash"
      mode: "0644"
