- name: install yay
  pacman:
    name: yay
    state: present

- name: install xclip
  pacman:
    name: xclip
    state: present

- name: install ripgrep
  pacman:
    name: ripgrep
    state: present

- name: install bat
  pacman:
    name: bat
    state: present

- name: install fzf
  pacman:
    name: fzf
    state: present

- name: install tig
  pacman:
    name: tig
    state: present

- name: install neovim
  pacman:
    name: neovim
    state: present

    #- name: install python-neovim
    #pacman:
    #name: python-neovim
    #state: present

- name: install python-pipenv
  pacman:
    name: python-pipenv
    state: present

- name: install vagrant
  pacman:
    name: vagrant
    state: present

- name: install terminator
  pacman:
    name: terminator
    state: present

- name: install gnumeric
  pacman:
    name: gnumeric
    state: present

- name: install synapse
  pacman:
    name: synapse
    state: present

- name: Run the equivalent of "pacman -Syu" as a separate step
  pacman:
    update_cache: yes
    upgrade: yes
