on:
  push:
    branches:
      - master

env:
  AWS_ROLE_ARN: arn:aws:iam::327379428311:role/dotfiles-ci-role
  ECR_REGISTRY: public.ecr.aws
  ECR_REPOSITORY: c5e8h2t0/dotfiles

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.ECR_REGISTRY }}
        env:
          AWS_REGION: us-east-1
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
